// Available tokens for trading
export const tokens = [
  { symbol: "usdc", name: "USD Coin" },
  { symbol: "usdt", name: "Tether" },
  { symbol: "btc", name: "Bitcoin" },
  { symbol: "eth", name: "Ethereum" },
  { symbol: "sol", name: "Solana" },
  { symbol: "matic", name: "Polygon" },
  { symbol: "ada", name: "Cardano" },
  { symbol: "dot", name: "Polkadot" },
  { symbol: "doge", name: "Dogecoin" },
  { symbol: "avax", name: "Avalanche" },
  { symbol: "link", name: "Chainlink" },
  { symbol: "uni", name: "Uniswap" },
  { symbol: "atom", name: "Cosmos" },
  { symbol: "algo", name: "Algorand" },
  { symbol: "xlm", name: "Stellar" },
  { symbol: "near", name: "NEAR Protocol" },
  { symbol: "ftm", name: "Fantom" },
  { symbol: "ape", name: "ApeCoin" },
  { symbol: "sand", name: "The Sandbox" },
  { symbol: "mana", name: "Decentraland" },
  { symbol: "aave", name: "Aave" },
  { symbol: "crv", name: "Curve DAO" },
  { symbol: "snx", name: "Synthetix" },
  { symbol: "mkr", name: "Maker" },
  { symbol: "comp", name: "Compound" },
];
