// Available tokens for trading
export const tokens = [
  { symbol: "USDT", name: "Tether" },
  { symbol: "USDC", name: "USD Coin" },
  { symbol: "BTC", name: "Bitcoin" },
  { symbol: "ETH", name: "Ethereum" },
  { symbol: "SOL", name: "Solana" },
  { symbol: "MATIC", name: "Polygon" },
  { symbol: "ADA", name: "Cardano" },
  { symbol: "DOT", name: "Polkadot" },
  { symbol: "DOGE", name: "Dogecoin" },
  { symbol: "AVAX", name: "Avalanche" },
  { symbol: "LINK", name: "Chainlink" },
  { symbol: "UNI", name: "Uniswap" },
  { symbol: "ATOM", name: "Cosmos" },
  { symbol: "ALGO", name: "Algorand" },
  { symbol: "XLM", name: "Stellar" },
  { symbol: "NEAR", name: "NEAR Protocol" },
  { symbol: "FTM", name: "Fantom" },
  { symbol: "APE", name: "ApeCoin" },
  { symbol: "SAND", name: "The Sandbox" },
  { symbol: "MANA", name: "Decentraland" },
  { symbol: "AAVE", name: "Aave" },
  { symbol: "CRV", name: "Curve DAO" },
  { symbol: "SNX", name: "Synthetix" },
  { symbol: "MKR", name: "Maker" },
  { symbol: "COMP", name: "Compound" },
];

export const frequencies = [
  { value: "hourly", label: "Hourly" },
  { value: "daily", label: "Daily" },
  { value: "weekly", label: "Weekly" },
  { value: "biweekly", label: "Bi-weekly" },
  { value: "monthly", label: "Monthly" },
];
