version: "3.8"
services:
  agents:
    image: lachsbagel/moragents_dockers-agents:amd64-0.2.2
    build:
      dockerfile: Dockerfile
      context: ./agents
    ports:
      - "8080:5000"
    restart: always
    volumes:
      - agents_data:/var/lib/agents
      - ./agents/src:/app/src
    environment:
      - BASE_URL=http://ollama:11434
    networks:
      - ollama-network

  nginx:
    image: lachsbagel/moragents_dockers-nginx:amd64-0.2.2
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "3333:80"
    networks:
      - ollama-network

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge

volumes:
  agents_data:
  ollama_data: